### PR TITLE
Measure gas

### LINKED ISSUE #201: Measure, simulate and understand gas usage
Be nice to have a test, which measures gas usage on different changes to simulate costs

### PR DESCRIPTION
**Pull request by uivlis**
Fixes #201.

### CODE REVIEW

**Comment by posix4e** [comment]
This a good start. How do the gas costs display? What does it look like?

**Comment by uivlis** [comment]
During testing, it logs to console something like this:
```
...
      ✓ pays each recipient their corresponding amount (427ms)
Setup costs: 164716 wei.
BulkPayOut costs: 202482 wei.
Complete costs: 29608 wei.
...
```

**Comment by posix4e** [comment]
Would it be reasonable to set some max cumulative gas as a part of testing?

**Comment by uivlis** [comment]
You mean the tests to fail if max total gas reached? That would mean to define a max total gas for approx. 30 diferent tests.

**Comment by posix4e** [comment]
> You mean the tests to fail if max total gas reached? That would mean to define a max total gas for approx. 30 diferent tests.

Or maybe just one or two of the tests that we wanna assure. Just something that's less than manual

**Comment by uivlis** [comment]
I don't even know what standard to use when setting those limits... Do you have some limits in mind?

**Comment by posix4e** [comment]
> I don't even know what standard to use when setting those limits... Do you have some limits in mind?

Basic sanity checks. Pick a couple of things that would be bad to say increase by 5x.

**Comment by uivlis** [comment]
Sanity checks, checked.

**Pull request merged**
