### PR TITLE
bump Python to 3.7, update packages

### PR DESCRIPTION
**Pull request by e271828-**

### CODE REVIEW

**Comment by posix4e** [comment]
@rbval any reason why we use python 3.6 currently?

**Comment by posix4e** [comment]
@e271828- wanna bump the package version as well?

**Comment by gaieges** [comment]
lgtm, will defer approval to @rbval though

**Comment by Villux** [comment]
Added basemodel update to this

**Comment by e271828-** [comment]
@rbval which other services?

**Comment by rbval** [comment]
@e271828- bcs, paymentagent, loader, hmt-servers

**Comment by Villux** [comment]
any change to get this merged and to pypi today? :)

**Comment by Villux** [comment]
I removed my basemodel update.

**Pull request merged**
